version: "3"

vars:
  VENV_DIR: .venv
  VENV_BIN: "{{ .VENV_DIR }}/bin"
  PYTHON_BIN: "{{ .VENV_BIN }}/python3"
  PIP_BIN: "{{ .VENV_BIN }}/pip3"

env:
  PORT: 8001
  PATH: "{{ .VENV_BIN }}:$PATH"

dotenv: [".env", ".env.local"]

# Available tasks:
# - start (default)
# - clean
# - test
# - lint
# - format

tasks:
  default:
    cmds:
      - task: start

  start:
    deps:
      - install-python
      - install-yarn
    cmds:
      - PATH="{{ .VENV_BIN }}:$PATH" yarn start

  clean:
    cmds:
      - rm -rf static/css static/js/dist node_modules {{ .VENV_DIR }} .task

  test:
    deps:
      - install-python
      - install-yarn
    cmds:
      - PATH="{{ .VENV_BIN }}:$PATH" coverage run --source=. -m unittest discover tests
      - PATH="{{ .VENV_BIN }}:$PATH" yarn test-js --coverage

  lint:
    deps:
      - install-python
      - install-yarn
    cmds:
      - PATH="{{ .VENV_BIN }}:$PATH" yarn lint-python
      - PATH="{{ .VENV_BIN }}:$PATH" yarn lint-ts
      - PATH="{{ .VENV_BIN }}:$PATH" yarn lint-js
      - PATH="{{ .VENV_BIN }}:$PATH" yarn lint-scss

  format:
    deps:
      - install-python
      - install-yarn
    cmds:
      - PATH="{{ .VENV_BIN }}:$PATH" yarn format-python
      - PATH="{{ .VENV_BIN }}:$PATH" yarn format-prettier
      - npx stylelint --fix static/**/*.scss

  # Custom tools versioning setup (mise, python, node, etc.)
  setup-mise:
    internal: true
    desc: "Setup mise"
    preconditions:
      - which curl
    status:
      - ! which mise
    cmds:
      - curl https://mise.run | sh

  setup-tools:
    deps:
      - setup-mise
    cmds:
      - mise install

  # Python virtual environment
  venv:
    internal: true
    desc: "Setup python virtual environment"
    deps:
      - setup-tools
    status:
      - ! -f {{ .PYTHON_BIN }}
    cmds:
      - python3 -m venv .venv

  install-python:
    internal: true
    desc: "Install python packages"
    deps:
      - venv
    sources:
      - requirements.txt
    generates:
      - "{{ .VENV_DIR }}/*"
    cmds:
      - "{{ .PIP_BIN }} install -r requirements.txt"

  # Node.js package manager
  install-yarn:
    internal: true
    desc: "Install yarn packages"
    deps:
      - setup-tools
    status:
      - which yarn
      - which node
    sources:
      - yarn.lock
      - package.json
    generates:
      - "node_modules/**"
    cmds:
      - yarn install
