name: Form tests
on: [push, pull_request]

jobs:
  # test-playwright-forms:
  #   if: github.repository == 'canonical/ubuntu.com'
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4

  #   - uses: actions/setup-node@v4
  #     with:
  #       node-version: 20

  #   - name: Install dependencies
  #     run: yarn install --immutablee

  #   - name: Install dependencies
  #     run: npm install -g yarn && yarn

  #   - name: Install dotrun
  #     run: sudo pip3 install dotrun requests==2.31.0 # requests version is pinned to avoid breaking changes, can be removed once issue is resolved: https://github.com/docker/docker-py/issues/3256resolved: https://github.com/docker/docker-py/issues/3256

  #   - name: Install dependencies
  #     run: |
  #       sudo chmod -R 777 .
  #       dotrun install

  #   - name: Build assets and run dotrun
  #     run: |
  #       dotrun & sleep 5
  #         curl --head --fail --retry-delay 2 --retry 30 --retry-connrefused http://localhost:8001

  #   - name: Install Playwright Browsers
  #     run: yarn playwright install --with-deps

  #   - name: Run Playwright tests on modals
  #     env:
  #       PLAYWRIGHT_USER_ID: ${{ secrets.PLAYWRIGHT_USER_ID }}
  #       PLAYWRIGHT_USER_PASSWORD : ${{ secrets.PLAYWRIGHT_USER_PASSWORD }}
  #       TESTING: true
  #     run: yarn playwright test forms/form-generator.spec.ts

  test-marketo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.base_ref }}

      - name: Install node dependencies
        run: yarn install --immutable

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          
      - name: Get changed form-data.json files
        id: changed-files
        run: |
          MERGE_BASE=$(git merge-base origin/main HEAD)
          CHANGED_FORM_FILES=$(git diff --diff-filter=ACMRd --name-only $MERGE_BASE..HEAD -- 'templates/**/form-data.json' ':!templates/tests/**' | tr '\n' ' ')
          
          echo "Changed files: $CHANGED_FORM_FILES"
          echo "CHANGED_FORM_FILES=$CHANGED_FORM_FILES" >> $GITHUB_ENV

      # - name: Get changed form-data.json files in the templates folder
      #   id: changed-files
      #   run: |
      #     TARGET_SHA=$(git rev-parse $GITHUB_BASE_REF)
      #     CHANGED_FORM_FILES=$(git diff --diff-filter=ACMRd --name-only $TARGET_SHA $GITHUB_SHA -- 'templates/**/form-data.json' ':!templates/tests/**' | tr '\n' ' ')
      #     echo "CHANGED_FORM_FILES=$CHANGED_FORM_FILES" >> $GITHUB_ENV

      - name: Run Marketo tests for affected forms
        if: env.CHANGED_FORM_FILES != ''
        env:
          MARKETO_API_URL: "https://066-EOV-335.mktorest.com"
          MARKETO_API_CLIENT: ${{ secrets.MARKETO_API_CLIENT }}
          MARKETO_API_SECRET: ${{ secrets.MARKETO_API_SECRET }}
        run: |
          echo "The following files have changed: $CHANGED_FORM_FILES"
          python -m unittest tests.test_marketo